[Content]
Packages=
    # Secure Boot chain
    grub-efi-amd64-signed
    shim-signed

Bootable=enabled
Bootloader=grub
ShimBootloader=signed

KernelCommandLine=
    console=ttyS0,115200n8
    mem_encrypt=on
    iommu=nopt
    nvidia.NVreg_ConfidentialComputing=1
    lockdown=integrity
    module.sig_enforce=1
    acpi_no_initrd_table_override
